export interface Product {
  id: number;
  name: string;
  price: number;
  isAdded: boolean;
}

export const PRODUCTS: Product[] = [
  { id: 1, name: 'Laptop', price: 55000, isAdded: false },
  { id: 2, name: 'Phone', price: 28000, isAdded: false },
  { id: 3, name: 'Headphones', price: 4500, isAdded: false },
  { id: 4, name: 'Smartwatch', price: 9000, isAdded: false },
  { id: 5, name: 'Tablet', price: 18000, isAdded: false },
  { id: 6, name: 'Keyboard', price: 2500, isAdded: false },
  { id: 7, name: 'Mouse', price: 1200, isAdded: false },
  { id: 8, name: 'Monitor', price: 12000, isAdded: false },
  { id: 9, name: 'External Hard Drive', price: 5000, isAdded: false },
  { id: 10, name: 'USB Flash Drive', price: 600, isAdded: false },
  { id: 11, name: 'Bluetooth Speaker', price: 3500, isAdded: false },
  { id: 12, name: 'Gaming Console', price: 25000, isAdded: false },
  { id: 13, name: 'Camera', price: 42000, isAdded: false },
  { id: 14, name: 'Drone', price: 60000, isAdded: false },
  { id: 15, name: 'Printer', price: 8000, isAdded: false },
  { id: 16, name: 'Scanner', price: 7000, isAdded: false },
  { id: 17, name: 'Projector', price: 15000, isAdded: false },
  { id: 18, name: 'Router', price: 3500, isAdded: false },
  { id: 19, name: 'Smart TV', price: 38000, isAdded: false },
  { id: 20, name: 'VR Headset', price: 25000, isAdded: false },
  { id: 21, name: 'Fitness Tracker', price: 6000, isAdded: false },
  { id: 22, name: 'Microwave Oven', price: 7500, isAdded: false },
  { id: 23, name: 'Refrigerator', price: 48000, isAdded: false },
  { id: 24, name: 'Washing Machine', price: 42000, isAdded: false },
  { id: 25, name: 'Air Conditioner', price: 55000, isAdded: false },
  { id: 26, name: 'Ceiling Fan', price: 2500, isAdded: false },
  { id: 27, name: 'Electric Kettle', price: 1500, isAdded: false },
  { id: 28, name: 'Coffee Maker', price: 4000, isAdded: false },
  { id: 29, name: 'Blender', price: 2800, isAdded: false },
  { id: 30, name: 'Toaster', price: 1200, isAdded: false },
  { id: 31, name: 'Vacuum Cleaner', price: 10000, isAdded: false },
  { id: 32, name: 'Dishwasher', price: 50000, isAdded: false },
  { id: 33, name: 'Water Purifier', price: 12000, isAdded: false },
  { id: 34, name: 'Electric Stove', price: 25000, isAdded: false },
  { id: 35, name: 'Rice Cooker', price: 2500, isAdded: false },
  { id: 36, name: 'Hair Dryer', price: 2000, isAdded: false },
  { id: 37, name: 'Electric Shaver', price: 4500, isAdded: false },
  { id: 38, name: 'Iron', price: 1500, isAdded: false },
  { id: 39, name: 'Desk Lamp', price: 900, isAdded: false },
  { id: 40, name: 'Bookshelf', price: 6000, isAdded: false },
  { id: 41, name: 'Office Chair', price: 7500, isAdded: false },
  { id: 42, name: 'Standing Desk', price: 18000, isAdded: false },
  { id: 43, name: 'Sofa', price: 35000, isAdded: false },
  { id: 44, name: 'Dining Table', price: 28000, isAdded: false },
  { id: 45, name: 'Bed Frame', price: 32000, isAdded: false },
  { id: 46, name: 'Mattress', price: 25000, isAdded: false },
  { id: 47, name: 'Wardrobe', price: 30000, isAdded: false },
  { id: 48, name: 'Books', price: 500, isAdded: false },
  { id: 49, name: 'Board Game', price: 1800, isAdded: false },
  { id: 50, name: 'Toy Car', price: 800, isAdded: false }
]
